[kubernetes]
[kubernetes.expected]
services = [ "my-service", "my-other-service" ]
deployments = [ "my-app", "my-other-app" ]
[switchboard]
links = [
  {url = "https://{namespace}.some.team", name="App"},
]
actions = [
  {action = "get-secret", resource="some-secret", name="Secrets!"},
]